# Generated by Django 3.0.3 on 2020-03-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200216_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealers',
            name='dealer_of',
            field=models.CharField(choices=[('none', 'select a manufacturer'), ('mastercraft', 'Mastercraft'), ('moomba', 'Moomba'), ('stingray', 'Stingray'), ('cobalt', 'Cobalt'), ('bryant', 'Bryant'), ('four winns', 'Four Winns'), ('sea doo', 'Sea Doo'), ('malibu', 'Malibu'), ('bayliner', 'Bayliner'), ('starcraft', 'Startcraft'), ('sea ray', 'Sea Ray'), ('centurion', 'Centurion'), ('tige', 'Tige'), ('nautique', 'Nautique'), ('yamaha', 'Yamaha'), ('supra', 'Supra'), ('caravelle', 'Caravelle'), ('chaparral', 'Chaparral'), ('crownline', 'Crownline'), ('ebbtide', 'Ebbtide'), ('toyota', 'Toyota'), ('ndt', 'NDT'), ('not listed', 'Not Listed')], max_length=100, verbose_name='Manufacturer'),
        ),
    ]
