# Generated by Django 2.2.8 on 2020-02-16 06:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import towers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Towers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('manufacturer', models.CharField(choices=[('none', 'select a manufacturer'), ('mastercraft', 'Mastercraft'), ('moomba', 'Moomba'), ('stingray', 'Stingray'), ('cobalt', 'Cobalt'), ('bryant', 'Bryant'), ('four winns', 'Four Winns'), ('sea doo', 'Sea Doo'), ('malibu', 'Malibu'), ('bayliner', 'Bayliner'), ('starcraft', 'Startcraft'), ('centurion', 'Centurion'), ('tige', 'Tige'), ('nautique', 'Nautique'), ('yamaha', 'Yamaha'), ('supra', 'Supra'), ('ndt', 'NDT'), ('not_listed', 'Not Listed')], default=None, max_length=50)),
                ('start_year', models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1970), towers.models.max_value_current_year])),
                ('end_year', models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1970), towers.models.max_value_current_year])),
                ('model', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Towers',
            },
        ),
        migrations.CreateModel(
            name='TowerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qty', models.IntegerField(default=1)),
                ('style', models.CharField(choices=[('FL', 'Fullsize'), ('MN', 'Mini')], default='Fullsize', max_length=2)),
                ('finish', models.CharField(choices=[('BRUSHED', 'Brushed'), ('POWDER_COATED', 'Powder coated'), ('POLISHED', 'Polished')], default='Brushed', max_length=20)),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towers.Towers')),
            ],
            options={
                'verbose_name_plural': 'TowerOrders',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.CharField(choices=[('none', 'select a manufacturer'), ('mastercraft', 'Mastercraft'), ('moomba', 'Moomba'), ('stingray', 'Stingray'), ('cobalt', 'Cobalt'), ('bryant', 'Bryant'), ('four winns', 'Four Winns'), ('sea doo', 'Sea Doo'), ('malibu', 'Malibu'), ('bayliner', 'Bayliner'), ('starcraft', 'Startcraft'), ('centurion', 'Centurion'), ('tige', 'Tige'), ('nautique', 'Nautique'), ('yamaha', 'Yamaha'), ('supra', 'Supra'), ('ndt', 'NDT'), ('not_listed', 'Not Listed')], default=None, max_length=50)),
                ('image', models.ImageField(upload_to='photos/')),
                ('orientation', models.CharField(blank=True, choices=[('main', 'Main'), ('angled', 'Angled'), ('back', 'Back'), ('collapsed', 'Collapsed')], default=None, max_length=20)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Products')),
                ('tower', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='towers.Towers')),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Biminis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towers.Towers')),
            ],
            options={
                'verbose_name_plural': 'Biminis',
            },
        ),
        migrations.CreateModel(
            name='BiminiOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('BK', 'Black'), ('JR', 'Jockey Red'), ('LR', 'Logo Red'), ('OR', 'Orange'), ('BD', 'Burgandy'), ('PB', 'Pacific Blue'), ('CD', 'Concord'), ('SY', 'Sunflower Yellow'), ('TQ', 'Turquoise'), ('SB', 'Sky Blue'), ('TS', 'Toast'), ('NT', 'Natural'), ('CG', 'Cadet Grey'), ('CL', 'Charcoal Grey'), ('BR', 'Brown'), ('NY', 'Navy'), ('FG', 'Forest Green'), ('RB', 'Royal Blue'), ('TN', 'Tan'), ('PG', 'Persian Green')], default=('BK', 'Black'), max_length=20)),
                ('qty', models.IntegerField(default=1)),
                ('bimini', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towers.Biminis')),
            ],
            options={
                'verbose_name_plural': 'BiminiOrders',
            },
        ),
    ]
